services:
  - type: web
    name: summarease-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: HF_API_KEY
        value: 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
      - key: NODE_VERSION
        value: 20.9.0
    autoDeploy: false

  - type: web
    name: summarease-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: summarease-backend
          property: host
    autoDeploy: false
